import { useMemo } from "react";
import { useSelector } from "react-redux";

import {
  Button,
  Card,
  CardContent,
  Chip,
  Paper,
  Stack,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TablePagination,
  TableRow,
  Typography,
} from "@mui/material";

import usePagination from "../../hooks/usePagination";

const ReportsTable = ({
  search,
  category,
  format,
}) => {
  const { reports } = useSelector(
    (state) => state.reports
  );

  const {
    page,
    rowsPerPage,
    handleChangePage,
    handleChangeRowsPerPage,
  } = usePagination(0, 5);

  const reportData = useMemo(() => {
    return reports.filter((report) => {
      const matchesSearch =
        !search ||
        report.name
          .toLowerCase()
          .includes(search.toLowerCase());

      const matchesCategory =
        !category ||
        report.category === category;

      const matchesFormat =
        !format ||
        report.format === format;

      return (
        matchesSearch &&
        matchesCategory &&
        matchesFormat
      );
    });
  }, [reports, search, category, format]);

  const exportCSV = () => {
    const headers = [
      "Report Name",
      "Category",
      "Generated By",
      "Generated Date",
      "Format",
    ];

    const rows = reportData.map((report) => [
      report.name,
      report.category,
      report.generatedBy,
      report.generatedDate,
      report.format,
    ]);

    const csv = [
      headers.join(","),
      ...rows.map((row) => row.join(",")),
    ].join("\n");

    const blob = new Blob([csv], {
      type: "text/csv;charset=utf-8;",
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;
    link.download = "Reports.csv";
    link.click();

    URL.revokeObjectURL(url);
  };

  return (
    <Card elevation={3}>
      <CardContent>
        <Stack
          direction="row"
          justifyContent="space-between"
          alignItems="center"
          mb={3}
        >
          <Typography
            variant="h6"
            fontWeight="bold"
          >
            Available Reports
          </Typography>

          <Stack
            direction="row"
            spacing={2}
          >
            <Button
              variant="outlined"
              color="success"
            >
              Export Excel
            </Button>

            <Button
              variant="contained"
              onClick={exportCSV}
            >
              Export CSV
            </Button>
          </Stack>
        </Stack>

        <TableContainer component={Paper}>
          <Table>
            <TableHead>
              <TableRow>
                <TableCell>
                  <strong>Report Name</strong>
                </TableCell>

                <TableCell>
                  <strong>Category</strong>
                </TableCell>

                <TableCell>
                  <strong>Generated By</strong>
                </TableCell>

                <TableCell>
                  <strong>Date</strong>
                </TableCell>

                <TableCell>
                  <strong>Format</strong>
                </TableCell>
              </TableRow>
            </TableHead>

            <TableBody>
              {reportData.length > 0 ? (
                reportData
                  .slice(
                    page * rowsPerPage,
                    page * rowsPerPage +
                      rowsPerPage
                  )
                  .map((report) => (
                    <TableRow
                      hover
                      key={report.id}
                    >
                      <TableCell>
                        {report.name}
                      </TableCell>

                      <TableCell>
                        {report.category}
                      </TableCell>

                      <TableCell>
                        {report.generatedBy}
                      </TableCell>

                      <TableCell>
                        {report.generatedDate}
                      </TableCell>

                      <TableCell>
                        <Chip
                          label={report.format}
                          color="primary"
                          size="small"
                        />
                      </TableCell>
                    </TableRow>
                  ))
              ) : (
                <TableRow>
                  <TableCell
                    colSpan={5}
                    align="center"
                  >
                    No reports found.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </TableContainer>

        <TablePagination
          component="div"
          count={reportData.length}
          page={page}
          rowsPerPage={rowsPerPage}
          rowsPerPageOptions={[5, 10, 20]}
          onPageChange={handleChangePage}
          onRowsPerPageChange={
            handleChangeRowsPerPage
          }
        />
      </CardContent>
    </Card>
  );
};

export default ReportsTable;